### ISSUE TITLE
Travis build status failing in README.md

### ISSUE THREAD

**Issue by kbougy** [coolfriends/discordbot#13]
Here is what I'm referring to:

[![Build Status](https://travis-ci.org/coolfriends/discordbot.svg?branch=update-readme)](https://travis-ci.org/coolfriends/discordbot)

My first though is that the branch being set to update-readme may be causing the issue. Can we get this set to master?

**Comment by JordanRushing** [comment]
Yep I'll fix this

**Comment by JordanRushing** [comment]
Done and merged
